# netlify.toml - 动态版本配置
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# 使用 Next.js Runtime 支持 SSR
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions 配置
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 环境变量
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://nexusk.fun"
  NEXT_PUBLIC_APP_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--nexusk-website.netlify.app"
  NEXT_PUBLIC_APP_ENV = "preview"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "https://branch-$BRANCH--nexusk-website.netlify.app"
  NEXT_PUBLIC_APP_ENV = "development"

# 头部配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.{js,css,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Edge Functions（可选）
[[edge_functions]]
  function = "server-status"
  path = "/edge/server-status"

# 重定向
[[redirects]]
  from = "/server"
  to = "/nexus"
  status = 301

# API 重定向到 Netlify Functions
[[redirects]]
  from = "/api/legacy/*"
  to = "/.netlify/functions/:splat"
  status = 200