# netlify.toml - 修复版本
[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# 禁用 Next.js 插件，使用手动配置
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# 静态文件缓存优化
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 字体文件缓存
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 图片优化
[[headers]]
  for = "/*.{jpg,jpeg,png,webp,avif}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 移除 SPA 重定向，因为我们是静态导出
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200